name: comnecter_mobile
description: A Flutter app for connecting with people nearby using radar technology.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  flutter_hooks: ^0.20.3
  flutter_animate: ^4.2.0+1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  confetti: ^0.7.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  share_plus: ^7.2.1
  animated_text_kit: ^4.2.2
  
  # Firebase Core
  firebase_core: ^2.24.2
  
  # Firebase Authentication
  firebase_auth: ^4.15.3
  
  # Cloud Firestore Database
  cloud_firestore: ^4.13.6
  
  # Firebase Storage
  firebase_storage: ^11.5.6
  
  # Firebase Messaging (Push Notifications)
  firebase_messaging: ^14.7.10
  
  # Firebase Analytics
  firebase_analytics: ^10.7.4
  connectivity_plus: ^6.1.5
  
  # Firebase Crashlytics
  # firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_icon.png
    - assets/sounds/
    - assets/images/
    - assets/icons/

# Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
