name: comnecter_mobile
description: A Flutter app for connecting with people nearby using radar technology.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  flutter_hooks: ^0.20.3
  flutter_animate: ^4.2.0+1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  confetti: ^0.7.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/app_icon.png
    - assets/sounds/
    - assets/images/
    - assets/icons/
