// This file will be automatically generated by FlutterFire CLI.
// To generate it, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase options for different platforms.
/// This will be generated by FlutterFire CLI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for Comnecter Mobile
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3f8zAdKxm8HXWHJCiMNwVW0kkZhERjhw',
    appId: '1:887865244956:web:temp-web-app-id',
    messagingSenderId: '887865244956',
    projectId: 'comnecter-mobile-aa30b',
    authDomain: 'comnecter-mobile-aa30b.firebaseapp.com',
    storageBucket: 'comnecter-mobile-aa30b.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3f8zAdKxm8HXWHJCiMNwVW0kkZhERjhw',
    appId: '1:887865244956:android:8c44b99280759292e9ced9',
    messagingSenderId: '887865244956',
    projectId: 'comnecter-mobile-aa30b',
    storageBucket: 'comnecter-mobile-aa30b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRxV7kQcVxxYkkTGX1hHH2j0TB6uVVVZA',
    appId: '1:887865244956:ios:e247049fd3cda1a3e9ced9',
    messagingSenderId: '887865244956',
    projectId: 'comnecter-mobile-aa30b',
    storageBucket: 'comnecter-mobile-aa30b.firebasestorage.app',
    iosBundleId: 'com.comnecter.mobile.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRxV7kQcVxxYkkTGX1hHH2j0TB6uVVVZA',
    appId: '1:887865244956:ios:e247049fd3cda1a3e9ced9',
    messagingSenderId: '887865244956',
    projectId: 'comnecter-mobile-aa30b',
    storageBucket: 'comnecter-mobile-aa30b.firebasestorage.app',
    iosBundleId: 'com.comnecter.mobile.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3f8zAdKxm8HXWHJCiMNwVW0kkZhERjhw',
    appId: '1:887865244956:android:8c44b99280759292e9ced9',
    messagingSenderId: '887865244956',
    projectId: 'comnecter-mobile-aa30b',
    storageBucket: 'comnecter-mobile-aa30b.firebasestorage.app',
  );
}
